- name: ArgoCD セットアップ
  hosts: main-master
  become: false
  tasks:
    - name: ArgoCD用のNamespace作成
      kubernetes.core.k8s:
        name: "argocd"
        kind: Namespace
        state: present
        kubeconfig: /home/ec2-user/.kube/config

    - name: ArgoCD Helm レポジトリ追加
      kubernetes.core.helm_repository:
        name: argo
        repo_url: "https://argoproj.github.io/argo-helm"

    - name: Helm レポジトリ更新
      command: helm repo update

    - name: LBCのWebhook設定削除
      shell: |
        kubectl delete mutatingwebhookconfigurations mservice.elbv2.k8s.aws --ignore-not-found
        kubectl delete validatingwebhookconfigurations vservice.elbv2.k8s.aws --ignore-not-found
      environment:
        KUBECONFIG: /home/ec2-user/.kube/config
      ignore_errors: yes

    - name: ArgoCD インストール
      kubernetes.core.helm:
        name: argocd
        chart_ref: argo/argo-cd
        release_namespace: "argocd"
        create_namespace: true
        wait: true
        values:
          server:
            service:
              type: NodePort
              nodePorts:
                http: 30080
            extraArgs:
              - --insecure

    - name: CRDの存在確認
      kubernetes.core.k8s_info:
        kind: CustomResourceDefinition
        name: applications.argoproj.io
      register: crd_info
      until: crd_info.resources | length > 0
      retries: 10
      delay: 5

    - name: ArgoCD root Applicationの作成
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: root-app
            namespace: argocd
          spec:
            project: default
            source:
              repoURL: https://github.com/kanei0415/ktcloud-k8s-argocd-manifest.git
              targetRevision: HEAD
              path: Setup
            destination:
              server: https://kubernetes.default.svc
              namespace: default
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
                - CreateNamespace=true
