- name: containerdのセットアップ
  hosts: all
  become: true
  tasks:
    - name: containerdのインストール
      ansible.builtin.dnf:
        name: containerd
        state: present

    - name: containerdの初期設定ファイルの生成
      ansible.builtin.shell: |
        mkdir -p /etc/containerd
        containerd config default > /etc/containerd/config.toml

    - name: SystemdCgroupの有効化
      ansible.builtin.replace:
        path: /etc/containerd/config.toml
        regexp: "SystemdCgroup = false"
        replace: "SystemdCgroup = true"

    - name: IPv4ポワーディングの有効化
      ansible.builtin.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        reload: true

    - name: containerdサービスの有効化と開始
      ansible.builtin.systemd:
        name: containerd
        state: started
        enabled: true
