- name: Helmのセットアップ
  hosts: main-master
  become: true
  vars:
    helm_version: "v3.14.0"
    arch: "amd64"

  tasks:
    - name: Helmのインストール
      unarchive:
        src: "https://get.helm.sh/helm-{{ helm_version }}-linux-{{ arch }}.tar.gz"
        dest: /tmp
        remote_src: true

    - name: Helmバイナリを/usr/local/binにコピー
      copy:
        src: "/tmp/linux-{{ arch }}/helm"
        dest: /usr/local/bin/helm
        mode: "0755"
        remote_src: true

    - name: Helmのインストール確認
      command: helm version
      register: helm_result
