[ap-northeast-2a-masters]
10.0.2.216
10.0.2.195

[ap-northeast-2a-workers]
10.0.2.80

[main-master]
main-master ansible_host=10.0.4.232

[ap-northeast-2b-workers]
10.0.4.44
10.0.4.136

[ap-northeast-2a-masters:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ec2-user@43.203.173.29 -i ~/.ssh/ktcloud-bastion-node-key"'

[ap-northeast-2a-workers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ec2-user@43.203.173.29 -i ~/.ssh/ktcloud-bastion-node-key"'

[main-master:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ec2-user@43.203.147.220 -i ~/.ssh/ktcloud-bastion-node-key"'

[ap-northeast-2b-workers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ec2-user@43.203.147.220 -i ~/.ssh/ktcloud-bastion-node-key"'

[all:vars]
ansible_port=22
ansible_user=ec2-user
ansible_ssh_private_key_file=~/.ssh/ktcloud-bastion-node-key
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
nlb_dns_name=kt-cloud-nlb-c7ec861653c9f975.elb.ap-northeast-2.amazonaws.com
control_plane_endpoint="kt-cloud-nlb-c7ec861653c9f975.elb.ap-northeast-2.amazonaws.com:6443"
vpc_id=vpc-04171f0402da29cbe
a_master_01_private_ip=10.0.2.216
a_master_02_private_ip=10.0.2.195
b_master_01_private_ip=10.0.4.232