[ap-northeast-2a-masters]
10.0.2.103
10.0.2.62

[ap-northeast-2a-workers]
10.0.2.167

[main-master]
main-master ansible_host=10.0.4.239

[ap-northeast-2b-workers]
10.0.4.23
10.0.4.115

[ap-northeast-2a-masters:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ec2-user@52.78.76.224 -i ~/.ssh/ktcloud-bastion-node-key"'

[ap-northeast-2a-workers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ec2-user@52.78.76.224 -i ~/.ssh/ktcloud-bastion-node-key"'

[main-master:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ec2-user@16.184.40.140 -i ~/.ssh/ktcloud-bastion-node-key"'

[ap-northeast-2b-workers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ec2-user@16.184.40.140 -i ~/.ssh/ktcloud-bastion-node-key"'

[all:vars]
ansible_port=22
ansible_user=ec2-user
ansible_ssh_private_key_file=~/.ssh/ktcloud-bastion-node-key
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
nlb_dns_name=kt-cloud-nlb-4b3e032838bdcdb5.elb.ap-northeast-2.amazonaws.com
control_plane_endpoint="kt-cloud-nlb-4b3e032838bdcdb5.elb.ap-northeast-2.amazonaws.com:6443"
vpc_id=vpc-0a68f021b2ad071bc