[ap-northeast-2a-masters]
10.0.2.231
10.0.2.118

[ap-northeast-2a-workers]
10.0.2.114

[main-master]
main-master ansible_host=10.0.4.203

[ap-northeast-2b-workers]
10.0.4.95
10.0.4.80

[ap-northeast-2a-masters:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ec2-user@13.125.7.2 -i ~/.ssh/ktcloud-bastion-node-key"'

[ap-northeast-2a-workers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ec2-user@13.125.7.2 -i ~/.ssh/ktcloud-bastion-node-key"'

[main-master:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ec2-user@43.203.216.38 -i ~/.ssh/ktcloud-bastion-node-key"'

[ap-northeast-2b-workers:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ec2-user@43.203.216.38 -i ~/.ssh/ktcloud-bastion-node-key"'

[all:vars]
ansible_port=22
ansible_user=ec2-user
ansible_ssh_private_key_file=~/.ssh/ktcloud-bastion-node-key
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
nlb_dns_name=kt-cloud-nlb-451defe089f516d3.elb.ap-northeast-2.amazonaws.com
control_plane_endpoint="kt-cloud-nlb-451defe089f516d3.elb.ap-northeast-2.amazonaws.com:6443"
vpc_id=vpc-01bbf1d360602a525
a_master_01_private_ip=10.0.2.231
a_master_02_private_ip=10.0.2.118
b_master_01_private_ip=10.0.4.203