- name: KubernetesクラスタのマスターノードのJoin情報の取得
  hosts: main-master
  become: true
  tasks:
    - name: 証明書キーの生成
      ansible.builtin.shell: kubeadm init phase upload-certs --upload-certs | tail -n 1
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: cert_key_raw

    - name: Joinコマンドの生成
      ansible.builtin.shell: kubeadm token create --print-join-command
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: join_cmd_raw

    - name: Joinコマンドと証明書キーの共有用ホストの追加
      ansible.builtin.add_host:
        name: "K8S_VARS_HOLDER"
        shared_join_cmd: "{{ join_cmd_raw.stdout | trim }}"
        shared_cert_key: "{{ cert_key_raw.stdout | trim }}"

- name: KubernetesクラスタのマスターノードのJoin
  hosts: ap-northeast-2a-masters
  become: true
  tasks:
    - name: Joinコマンドの実行
      ansible.builtin.shell: >
        {{ hostvars['K8S_VARS_HOLDER']['shared_join_cmd'] }} --control-plane
        --certificate-key {{ hostvars['K8S_VARS_HOLDER']['shared_cert_key'] }}
        --cri-socket unix:///var/run/containerd/containerd.sock
      register: master_join_result
      when: hostvars['K8S_VARS_HOLDER']['shared_join_cmd'] is defined
      failed_when:
        - master_join_result.rc != 0
        - "'already exists' not in master_join_result.stderr"
