- name: Kubernetesパッケージのインストール
  hosts: all
  become: true
  tasks:
    - name: Kubernetesリポジトリの追加
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/kubernetes.repo
        mode: "0644"
        content: |
          [kubernetes]
          name=Kubernetes
          baseurl=https://pkgs.k8s.io/core:/stable:/v1.30/rpm/
          enabled=1
          gpgcheck=1
          gpgkey=https://pkgs.k8s.io/core:/stable:/v1.30/rpm/repodata/repomd.xml.key

    - name: dnfキャッシュのクリア
      ansible.builtin.shell: dnf clean all
      become: true

    - name: kubelet、kubeadm、kubectlのインストール
      ansible.builtin.dnf:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: kubeletサービスの有効化
      ansible.builtin.systemd:
        name: kubelet
        enabled: true
