- import_playbook: k8s-pre-setup.yaml
- import_playbook: k8s-pkg-install.yaml
- import_playbook: containerd-setup.yaml

- import_playbook: master-init.yaml
- import_playbook: master-cni-setup.yaml
- import_playbook: master-python-setup.yaml

- import_playbook: join-master.yaml
- import_playbook: join-worker.yaml

- import_playbook: helm-setup.yaml

- import_playbook: nlb-setup.yaml

- import_playbook: traefik-setup.yaml
