- name: Kubernetesクラスタのマスターノードの初期化
  hosts: main-master
  become: true
  tasks:
    - name: containerdサービスの開始と有効化
      ansible.builtin.systemd:
        name: containerd
        state: started
        enabled: true

    - name: Kubernetesの設定ディレクトリを作成
      ansible.builtin.file:
        path: /etc/kubernetes
        state: directory
        mode: "0755"
      become: true

    - name: kubeadmの設定ファイルをテンプレートから生成
      ansible.builtin.template:
        src: ./configuration/kubeadm-config.yaml.j2
        dest: /etc/kubernetes/kubeadm-config.yaml
        mode: "0644"

    - name: kubeadm initコマンドの実行
      ansible.builtin.shell: |
        kubeadm init --config /etc/kubernetes/kubeadm-config.yaml --upload-certs
      register: init_output
      args:
        creates: /etc/kubernetes/admin.conf

    - name: kubectlのためのkubeconfig設定
      ansible.builtin.file:
        path: /home/ec2-user/.kube
        state: directory
        mode: "0755"
        owner: ec2-user

    - name: configファイルのコピー
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ec2-user/.kube/config
        remote_src: true
        owner: ec2-user
        mode: "0600"
