- name: KubernetesクラスタのCNIプラグインセットアップ
  hosts: main-master
  become: true
  tasks:
    - name: Calicoネットワークプラグインの適用
      become: false
      ansible.builtin.shell: |
        kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/calico.yaml
