- name: MasterノードにPythonとKubernetesライブラリをインストール
  hosts: main-master
  become: true
  tasks:
    - name: Python3-pipインストール
      yum:
        name: python3-pip
        state: present

    - name: kubernetesパイソンライブラリインストール
      pip:
        name:
          - kubernetes
          - PyYAML
        executable: pip3
