- name: Traefik Ingress Controllerインストール
  hosts: main-master
  become: yes
  vars:
    traefik_namespace: "traefik"

  tasks:
    - name: Traefik用のNamespace作成
      kubernetes.core.k8s:
        name: "{{ traefik_namespace }}"
        kind: Namespace
        state: present
        kubeconfig: /home/ec2-user/.kube/config

    - name: Traefik Helm レポジトリ追加
      kubernetes.core.helm_repository:
        name: traefik
        repo_url: "https://traefik.github.io/charts"

    - name: Helm レポジトリ更新
      command: helm repo update

    - name: LBCのWebhook設定削除
      shell: |
        kubectl delete mutatingwebhookconfigurations mservice.elbv2.k8s.aws --ignore-not-found
        kubectl delete validatingwebhookconfigurations vservice.elbv2.k8s.aws --ignore-not-found
      environment:
        KUBECONFIG: /home/ec2-user/.kube/config
      ignore_errors: yes

    - name: Traefik Ingress Controllerインストール
      kubernetes.core.helm:
        name: traefik
        chart_ref: traefik/traefik
        release_namespace: "{{ traefik_namespace }}"
        kubeconfig: /home/ec2-user/.kube/config
        values:
          service:
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-type: "external"
              service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
              service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
          ingressClass:
            enabled: true
            isDefaultClass: true
